// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _predictionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpredictionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stocksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _codeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrealtimeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recognizestockimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfinancialreportMw() []app.HandlerFunc {
	// your code...
	return nil
}
