// Code generated by Kitex v1.20.0. DO NOT EDIT.

package aiservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	ai "stock_assistant/backend/gateway/kitex_gen/ai"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetPrediction(ctx context.Context, req *ai.GetPredictionRequest, callOptions ...callopt.Option) (r *ai.GetPredictionResponse, err error)
	ImageRecognition(ctx context.Context, req *ai.ImageRecognitionRequest, callOptions ...callopt.Option) (r *ai.ImageRecognitionResponse, err error)
	MarketReview(ctx context.Context, req *ai.MarketReviewRequest, callOptions ...callopt.Option) (r *ai.MarketReviewResponse, err error)
	AnalyzeMarket(ctx context.Context, req *ai.MarketAnalysisRequest, callOptions ...callopt.Option) (r *ai.MarketAnalysisResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIServiceClient struct {
	*kClient
}

func (p *kAIServiceClient) GetPrediction(ctx context.Context, req *ai.GetPredictionRequest, callOptions ...callopt.Option) (r *ai.GetPredictionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPrediction(ctx, req)
}

func (p *kAIServiceClient) ImageRecognition(ctx context.Context, req *ai.ImageRecognitionRequest, callOptions ...callopt.Option) (r *ai.ImageRecognitionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ImageRecognition(ctx, req)
}

func (p *kAIServiceClient) MarketReview(ctx context.Context, req *ai.MarketReviewRequest, callOptions ...callopt.Option) (r *ai.MarketReviewResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarketReview(ctx, req)
}

func (p *kAIServiceClient) AnalyzeMarket(ctx context.Context, req *ai.MarketAnalysisRequest, callOptions ...callopt.Option) (r *ai.MarketAnalysisResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AnalyzeMarket(ctx, req)
}
