// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"stock_assistant/backend/gateway/config"
	"stock_assistant/backend/gateway/biz/rpc"
	api "stock_assistant/backend/gateway/biz/handler/api"
)

func main() {
	if err := config.Init(); err != nil {
		panic(err)
	}
	rpc.Init()
	rpc.InitAI()
	rpc.InitKnowledgeGraph()
	addrValue := ":8080"
	cfg := config.Get()
	if cfg != nil && cfg.Server != nil && cfg.Server.Addr != "" {
		addrValue = cfg.Server.Addr
	}
	h := server.Default(
		server.WithHostPorts(addrValue),
		server.WithReadTimeout(60*time.Second),
		server.WithWriteTimeout(60*time.Second),
		server.WithIdleTimeout(60*time.Second),
		server.WithMaxRequestBodySize(10*1024*1024), // 10MB
	)

	h.Use(cors.Default())

	register(h)
	h.GET("/api/akshare/macro", api.GetAkShareMacro)
	h.GET("/api/akshare/news", api.GetAkShareNews)
	h.Spin()
}
