// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"stock_assistant/backend/gateway/biz/rpc"
)

func main() {
	rpc.Init()
	rpc.InitAI()
	h := server.Default(
		server.WithHostPorts(":8080"),
		server.WithReadTimeout(60*time.Second),
		server.WithWriteTimeout(60*time.Second),
		server.WithIdleTimeout(60*time.Second),
		server.WithMaxRequestBodySize(10*1024*1024), // 10MB
	)

	h.Use(cors.Default())

	register(h)
	h.Spin()
}
