// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"stock_assistant/backend/gateway/biz/rpc"
)

func main() {
	rpc.Init()
	rpc.InitAI()
	h := server.Default(server.WithHostPorts(":8080"))

	register(h)
	h.Spin()
}
