// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "stock_assistant/backend/gateway/biz/handler"
	"stock_assistant/backend/gateway/biz/router"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// Manual routes
	router.RegisterManualRoutes(r)
}
