// Code generated by Kitex v1.20.0. DO NOT EDIT.

package aiservice

import (
	client "code.byted.org/kite/kitex/client"
	"context"
	"errors"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	ai "stock_assistant/backend/ai_service/kitex_gen/ai"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetPrediction": kitex.NewMethodInfo(
		getPredictionHandler,
		newAIServiceGetPredictionArgs,
		newAIServiceGetPredictionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ImageRecognition": kitex.NewMethodInfo(
		imageRecognitionHandler,
		newAIServiceImageRecognitionArgs,
		newAIServiceImageRecognitionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	aIServiceServiceInfo                = NewServiceInfo()
	aIServiceServiceInfoForClient       = NewServiceInfoForClient()
	aIServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aIServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aIServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AIService"
	handlerType := (*ai.AIService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.20.0",
		Extra:           extra,
	}
	return svcInfo
}

func getPredictionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceGetPredictionArgs)
	realResult := result.(*ai.AIServiceGetPredictionResult)
	success, err := handler.(ai.AIService).GetPrediction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceGetPredictionArgs() interface{} {
	return ai.NewAIServiceGetPredictionArgs()
}

func newAIServiceGetPredictionResult() interface{} {
	return ai.NewAIServiceGetPredictionResult()
}

func imageRecognitionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai.AIServiceImageRecognitionArgs)
	realResult := result.(*ai.AIServiceImageRecognitionResult)
	success, err := handler.(ai.AIService).ImageRecognition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIServiceImageRecognitionArgs() interface{} {
	return ai.NewAIServiceImageRecognitionArgs()
}

func newAIServiceImageRecognitionResult() interface{} {
	return ai.NewAIServiceImageRecognitionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetPrediction(ctx context.Context, req *ai.GetPredictionRequest) (r *ai.GetPredictionResponse, err error) {
	var _args ai.AIServiceGetPredictionArgs
	_args.Req = req
	var _result ai.AIServiceGetPredictionResult
	if err = p.c.Call(ctx, "GetPrediction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ImageRecognition(ctx context.Context, req *ai.ImageRecognitionRequest) (r *ai.ImageRecognitionResponse, err error) {
	var _args ai.AIServiceImageRecognitionArgs
	_args.Req = req
	var _result ai.AIServiceImageRecognitionResult
	if err = p.c.Call(ctx, "ImageRecognition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
