// Code generated by Kitex v1.20.0. DO NOT EDIT.

package stockservice

import (
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"context"
	stock "stock_assistant/backend/stock_service/kitex_gen/stock"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetRealtime(ctx context.Context, req *stock.GetRealtimeRequest, callOptions ...callopt.Option) (r *stock.GetRealtimeResponse, err error)
	GetFinancialReport(ctx context.Context, req *stock.GetFinancialReportRequest, callOptions ...callopt.Option) (r *stock.GetFinancialReportResponse, err error)
	GetMarketSectors(ctx context.Context, req *stock.GetMarketSectorsRequest, callOptions ...callopt.Option) (r *stock.GetMarketSectorsResponse, err error)
	GetLimitUpPool(ctx context.Context, req *stock.GetLimitUpPoolRequest, callOptions ...callopt.Option) (r *stock.GetLimitUpPoolResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kStockServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStockServiceClient struct {
	*kClient
}

func (p *kStockServiceClient) GetRealtime(ctx context.Context, req *stock.GetRealtimeRequest, callOptions ...callopt.Option) (r *stock.GetRealtimeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRealtime(ctx, req)
}

func (p *kStockServiceClient) GetFinancialReport(ctx context.Context, req *stock.GetFinancialReportRequest, callOptions ...callopt.Option) (r *stock.GetFinancialReportResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFinancialReport(ctx, req)
}

func (p *kStockServiceClient) GetMarketSectors(ctx context.Context, req *stock.GetMarketSectorsRequest, callOptions ...callopt.Option) (r *stock.GetMarketSectorsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMarketSectors(ctx, req)
}

func (p *kStockServiceClient) GetLimitUpPool(ctx context.Context, req *stock.GetLimitUpPoolRequest, callOptions ...callopt.Option) (r *stock.GetLimitUpPoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLimitUpPool(ctx, req)
}
