// Code generated by Kitex v1.20.0. DO NOT EDIT.

package stockservice

import (
	client "github.com/cloudwego/kitex/client"
	"context"
	"errors"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	stock "stock_assistant/backend/stock_service/kitex_gen/stock"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetRealtime": kitex.NewMethodInfo(
		getRealtimeHandler,
		newStockServiceGetRealtimeArgs,
		newStockServiceGetRealtimeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFinancialReport": kitex.NewMethodInfo(
		getFinancialReportHandler,
		newStockServiceGetFinancialReportArgs,
		newStockServiceGetFinancialReportResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	stockServiceServiceInfo                = NewServiceInfo()
	stockServiceServiceInfoForClient       = NewServiceInfoForClient()
	stockServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return stockServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StockService"
	handlerType := (*stock.StockService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stock",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.20.0",
		Extra:           extra,
	}
	return svcInfo
}

func getRealtimeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceGetRealtimeArgs)
	realResult := result.(*stock.StockServiceGetRealtimeResult)
	success, err := handler.(stock.StockService).GetRealtime(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceGetRealtimeArgs() interface{} {
	return stock.NewStockServiceGetRealtimeArgs()
}

func newStockServiceGetRealtimeResult() interface{} {
	return stock.NewStockServiceGetRealtimeResult()
}

func getFinancialReportHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock.StockServiceGetFinancialReportArgs)
	realResult := result.(*stock.StockServiceGetFinancialReportResult)
	success, err := handler.(stock.StockService).GetFinancialReport(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceGetFinancialReportArgs() interface{} {
	return stock.NewStockServiceGetFinancialReportArgs()
}

func newStockServiceGetFinancialReportResult() interface{} {
	return stock.NewStockServiceGetFinancialReportResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetRealtime(ctx context.Context, req *stock.GetRealtimeRequest) (r *stock.GetRealtimeResponse, err error) {
	var _args stock.StockServiceGetRealtimeArgs
	_args.Req = req
	var _result stock.StockServiceGetRealtimeResult
	if err = p.c.Call(ctx, "GetRealtime", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFinancialReport(ctx context.Context, req *stock.GetFinancialReportRequest) (r *stock.GetFinancialReportResponse, err error) {
	var _args stock.StockServiceGetFinancialReportArgs
	_args.Req = req
	var _result stock.StockServiceGetFinancialReportResult
	if err = p.c.Call(ctx, "GetFinancialReport", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
