// Code generated by hertz generator.

package api

import (
	"context"
	"io"

	api "stock_assistant/backend/gateway/biz/model/api"
	"stock_assistant/backend/gateway/biz/rpc"
	"stock_assistant/backend/gateway/kitex_gen/ai"
	"stock_assistant/backend/gateway/kitex_gen/stock"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetRealtime 获取实时股价
// @router /api/stocks/:code/realtime [GET]
func GetRealtime(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetRealtimeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用股票服务
	rpcReq := &stock.GetRealtimeRequest{
		Code: req.Code,
	}
	rpcResp, err := rpc.StockClient.GetRealtime(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	// 映射响应
	resp := &api.RealtimeResponse{}
	if rpcResp.Stock != nil {
		resp.Code = rpcResp.Stock.Code
		resp.Name = rpcResp.Stock.Name
		resp.CurrentPrice = rpcResp.Stock.CurrentPrice
		resp.ChangePercent = rpcResp.Stock.ChangePercent
		resp.Volume = rpcResp.Stock.Volume
		resp.Timestamp = rpcResp.Stock.Timestamp
	}

	c.JSON(consts.StatusOK, resp)
}

type GetEvaluationsReq struct {
	StockCode string `query:"code"`
	Limit     int32  `query:"limit"`
	Offset    int32  `query:"offset"`
}

type EvaluationRec struct {
	ID             string  `json:"id"`
	PredictionID   string  `json:"prediction_id"`
	StockCode      string  `json:"stock_code"`
	PredictionDate string  `json:"prediction_date"`
	InitialPrice   float64 `json:"initial_price"`
	Price1D        float64 `json:"price_1d"`
	Price2D        float64 `json:"price_2d"`
	Price3D        float64 `json:"price_3d"`
	Score          float64 `json:"score"`
	Status         string  `json:"status"`
	StockName      string  `json:"stock_name"`
}

type GetEvaluationsResp struct {
	Evaluations []*EvaluationRec `json:"evaluations"`
}

// GetEvaluations 获取评估记录
// @router /api/evaluations [GET]
func GetEvaluations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req GetEvaluationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetEvaluationsRequest{
		StockCode: req.StockCode,
		Limit:     req.Limit,
		Offset:    req.Offset,
	}
	rpcResp, err := rpc.StockClient.GetEvaluations(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &GetEvaluationsResp{
		Evaluations: make([]*EvaluationRec, 0),
	}
	for _, e := range rpcResp.Evaluations {
		// 尝试获取股票名称
		stockName := ""
		// 优化：实际场景应批量获取名称或由服务返回。
		// 由于此处不易修改 IDL，暂且逐个获取作为变通。
		// 使用短超时或忽略错误。
		if info, err := rpc.StockClient.GetRealtime(ctx, &stock.GetRealtimeRequest{Code: e.StockCode}); err == nil && info.Stock != nil {
			stockName = info.Stock.Name
		}

		resp.Evaluations = append(resp.Evaluations, &EvaluationRec{
			ID:             e.Id,
			PredictionID:   e.PredictionId,
			StockCode:      e.StockCode,
			PredictionDate: e.PredictionDate,
			InitialPrice:   e.InitialPrice,
			Price1D:        e.Price_1d,
			Price2D:        e.Price_2d,
			Price3D:        e.Price_3d,
			Score:          e.Score,
			Status:         e.Status,
			StockName:      stockName,
		})
	}

	c.JSON(consts.StatusOK, resp)
}

// GetFinancialReport 获取财务报告
// @router /api/stocks/:code/financial [GET]
func GetFinancialReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetFinancialReportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用股票服务
	rpcReq := &stock.GetFinancialReportRequest{
		Code: req.Code,
	}
	rpcResp, err := rpc.StockClient.GetFinancialReport(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	// 映射响应
	resp := &api.GetFinancialReportResponse{
		Reports: make([]*api.FinancialData, 0),
	}
	if rpcResp.Reports != nil {
		for _, r := range rpcResp.Reports {
			resp.Reports = append(resp.Reports, &api.FinancialData{
				ReportDate:   r.ReportDate,
				TotalRevenue: r.TotalRevenue,
				NetProfit:    r.NetProfit,
				Eps:          r.Eps,
				RevenueYoy:   r.RevenueYoy,
				ProfitYoy:    r.ProfitYoy,
			})
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// GetPrediction 获取预测
// @router /api/prediction/:code [POST]
func GetPrediction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PredictionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用 AI 服务
	rpcReq := &ai.GetPredictionRequest{
		Code:        req.Code,
		Days:        req.Days,
		IncludeNews: req.IncludeNews,
		Model:       req.Model,
	}
	rpcResp, err := rpc.AIClient.GetPrediction(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	if rpcResp.Result_ == nil {
		c.String(consts.StatusInternalServerError, "AI 服务返回结果为空")
		return
	}

	resp := &api.PredictionResponse{
		Code:        rpcResp.Result_.Code,
		Confidence:  rpcResp.Result_.Confidence,
		Analysis:    rpcResp.Result_.Analysis,
		NewsSummary: rpcResp.Result_.NewsSummary_,
	}

	c.JSON(consts.StatusOK, resp)
}

// RecognizeStockImage 识别股票图片
// @router /api/image/recognize [POST]
func RecognizeStockImage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ImageRecognitionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 读取图片文件
	fileHeader, err := c.FormFile("image")
	if err != nil {
		c.String(consts.StatusBadRequest, "缺少图片文件")
		return
	}

	file, err := fileHeader.Open()
	if err != nil {
		c.String(consts.StatusInternalServerError, "打开图片文件失败")
		return
	}
	defer file.Close()

	fileBytes, err := io.ReadAll(file)
	if err != nil {
		c.String(consts.StatusInternalServerError, "读取图片文件失败")
		return
	}

	model := c.PostForm("model")

	// 调用 AI 服务
	rpcReq := &ai.ImageRecognitionRequest{
		ImageData: fileBytes,
		Model:     model,
	}

	hlog.Info("正在调用 AI 服务进行图像识别...")
	rpcResp, err := rpc.AIClient.ImageRecognition(ctx, rpcReq)
	if err != nil {
		hlog.Errorf("AI 服务失败: %v", err)
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	hlog.Info("AI 服务返回成功")

	// 映射响应
	resp := &api.ImageRecognitionResponse{
		Stocks: make([]*api.RecognizedStock, 0),
	}

	if rpcResp.Stocks != nil {
		for _, s := range rpcResp.Stocks {
			resp.Stocks = append(resp.Stocks, &api.RecognizedStock{
				Code: s.Code,
				Name: s.Name,
			})
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// MarketReview 市场复盘
// @router /api/market/review [POST]
func MarketReview(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MarketReviewRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用 AI 服务
	rpcReq := &ai.MarketReviewRequest{
		Date:         req.Date,
		FocusSectors: req.FocusSectors,
	}

	rpcResp, err := rpc.AIClient.MarketReview(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.MarketReviewResponse{
		Summary:           rpcResp.Summary,
		SectorAnalysis:    rpcResp.SectorAnalysis,
		SentimentAnalysis: rpcResp.SentimentAnalysis,
		KeyRisks:          rpcResp.KeyRisks,
		Opportunities:     rpcResp.Opportunities,
	}

	c.JSON(consts.StatusOK, resp)
}

// GetSectorStocks 获取板块成分股
// @router /api/stock/sector/stocks [GET]
func GetSectorStocks(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetSectorStocksRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetSectorStocksRequest{
		SectorCode: req.SectorCode,
	}
	rpcResp, err := rpc.StockClient.GetSectorStocks(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.GetSectorStocksResponse{
		Stocks: make([]*api.SectorStockItem, 0),
	}
	if rpcResp.Stocks != nil {
		for _, s := range rpcResp.Stocks {
			resp.Stocks = append(resp.Stocks, &api.SectorStockItem{
				Code:          s.Code,
				Name:          s.Name,
				Price:         s.Price,
				ChangePercent: s.ChangePercent,
				Volume:        s.Volume,
				Amount:        s.Amount,
				MarketCap:     s.MarketCap,
			})
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// GetDragonTigerList 获取龙虎榜
// @router /api/stock/dragontiger/list [GET]
func GetDragonTigerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetDragonTigerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetDragonTigerListRequest{
		Date: req.Date,
	}
	rpcResp, err := rpc.StockClient.GetDragonTigerList(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.GetDragonTigerListResponse{
		Items: make([]*api.DragonTigerItem, 0),
	}

	if rpcResp.Items != nil {
		for _, item := range rpcResp.Items {
			// 映射席位
			buySeats := make([]*api.DragonTigerSeat, 0)
			for _, bs := range item.BuySeats {
				buySeats = append(buySeats, &api.DragonTigerSeat{
					Name:    bs.Name,
					BuyAmt:  bs.BuyAmt,
					SellAmt: bs.SellAmt,
					NetAmt:  bs.NetAmt,
					Tags:    bs.Tags,
				})
			}
			sellSeats := make([]*api.DragonTigerSeat, 0)
			for _, ss := range item.SellSeats {
				sellSeats = append(sellSeats, &api.DragonTigerSeat{
					Name:    ss.Name,
					BuyAmt:  ss.BuyAmt,
					SellAmt: ss.SellAmt,
					NetAmt:  ss.NetAmt,
					Tags:    ss.Tags,
				})
			}

			resp.Items = append(resp.Items, &api.DragonTigerItem{
				Code:          item.Code,
				Name:          item.Name,
				ClosePrice:    item.ClosePrice,
				ChangePercent: item.ChangePercent,
				Reason:        item.Reason,
				NetInflow:     item.NetInflow,
				BuySeats:      buySeats,
				SellSeats:     sellSeats,
			})
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// AnalyzeMarket 市场分析
// @router /api/market/analysis [POST]
func AnalyzeMarket(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MarketAnalysisRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &ai.MarketAnalysisRequest{
		Date: req.Date,
	}

	rpcResp, err := rpc.AIClient.AnalyzeMarket(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.MarketAnalysisResponse{
		HotStocks:         rpcResp.HotStocks,
		RecommendedStocks: rpcResp.RecommendedStocks,
		Risks:             rpcResp.Risks,
		Opportunities:     rpcResp.Opportunities,
		AnalysisSummary:   rpcResp.AnalysisSummary,
		SentimentScore:    rpcResp.SentimentScore,
		PolicyScore:       rpcResp.PolicyScore,
	}

	c.JSON(consts.StatusOK, resp)
}

// GetMarketSectors 获取市场板块
// @router /api/market/sectors [GET]
func GetMarketSectors(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetMarketSectorsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetMarketSectorsRequest{
		Type:  req.Type,
		Limit: req.Limit,
	}
	rpcResp, err := rpc.StockClient.GetMarketSectors(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.GetMarketSectorsResponse{
		Sectors: make([]*api.SectorInfo, 0),
	}
	for _, s := range rpcResp.Sectors {
		resp.Sectors = append(resp.Sectors, &api.SectorInfo{
			Code:          s.Code,
			Name:          s.Name,
			ChangePercent: s.ChangePercent,
			NetInflow:     s.NetInflow,
			TopStockName:  s.TopStockName,
			TopStockCode:  s.TopStockCode,
			Type:          s.Type,
		})
	}

	c.JSON(consts.StatusOK, resp)
}

// GetLimitUpPool 获取涨停池
// @router /api/market/limit_up [GET]
func GetLimitUpPool(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetLimitUpPoolRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetLimitUpPoolRequest{
		Date: req.Date,
	}
	rpcResp, err := rpc.StockClient.GetLimitUpPool(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.GetLimitUpPoolResponse{
		Stocks: make([]*api.LimitUpStock, 0),
	}
	for _, s := range rpcResp.Stocks {
		resp.Stocks = append(resp.Stocks, &api.LimitUpStock{
			Code:          s.Code,
			Name:          s.Name,
			Price:         s.Price,
			ChangePercent: s.ChangePercent,
			LimitUpType:   s.LimitUpType,
			Reason:        s.Reason,
			IsBroken:      s.IsBroken,
		})
	}

	c.JSON(consts.StatusOK, resp)
}

// GetOrCreateUser 获取或创建用户
// @router /api/user/login [POST]
func GetOrCreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetOrCreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetOrCreateUserRequest{
		Username: req.Username,
	}
	rpcResp, err := rpc.StockClient.GetOrCreateUser(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.GetOrCreateUserResponse{}
	if rpcResp.User != nil {
		resp.User = &api.User{
			ID:        rpcResp.User.Id,
			Username:  rpcResp.User.Username,
			CreatedAt: rpcResp.User.CreatedAt,
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// AddWatchlist 添加自选股
// @router /api/watchlist/add [POST]
func AddWatchlist(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AddWatchlistRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.AddWatchlistRequest{
		UserId:    req.UserID,
		StockCode: req.StockCode,
	}
	hlog.CtxInfof(ctx, "添加自选股请求: UserID=%s, StockCode=%s", req.UserID, req.StockCode)

	rpcResp, err := rpc.StockClient.AddWatchlist(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, &api.AddWatchlistResponse{Success: rpcResp.Success})
}

// GetWatchlist 获取自选股列表
// @router /api/watchlist/list [GET]
func GetWatchlist(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetWatchlistRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetWatchlistRequest{
		UserId: req.UserID,
	}
	rpcResp, err := rpc.StockClient.GetWatchlist(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.GetWatchlistResponse{
		Items: make([]*api.WatchlistItem, 0),
	}
	for _, item := range rpcResp.Items {
		resp.Items = append(resp.Items, &api.WatchlistItem{
			StockCode: item.StockCode,
			Tags:      item.Tags,
			AddedAt:   item.AddedAt,
		})
	}

	c.JSON(consts.StatusOK, resp)
}

// RemoveWatchlist 移除自选股
// @router /api/watchlist/remove [POST]
func RemoveWatchlist(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RemoveWatchlistRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.RemoveWatchlistRequest{
		UserId:    req.UserID,
		StockCode: req.StockCode,
	}
	rpcResp, err := rpc.StockClient.RemoveWatchlist(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, &api.RemoveWatchlistResponse{Success: rpcResp.Success})
}

// GetHistoricalKline 获取历史K线
// @router /api/stock/kline [GET]
func GetHistoricalKline(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetHistoricalKlineRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.GetHistoricalKlineRequest{
		StockCode: req.StockCode,
		Days:      req.Days,
	}
	rpcResp, err := rpc.StockClient.GetHistoricalKline(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := &api.GetHistoricalKlineResponse{
		Klines: make([]*api.Kline, 0),
	}
	for _, k := range rpcResp.Klines {
		resp.Klines = append(resp.Klines, &api.Kline{
			Date:   k.Date,
			Open:   k.Open,
			Close:  k.Close,
			High:   k.High,
			Low:    k.Low,
			Volume: k.Volume,
		})
	}

	c.JSON(consts.StatusOK, resp)
}

// DeleteEvaluation 删除评估
// @router /api/evaluations/:id [DELETE]
func DeleteEvaluation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteEvaluationRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcReq := &stock.DeleteEvaluationRequest{
		Id: req.Id,
	}
	rpcResp, err := rpc.StockClient.DeleteEvaluation(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, &api.DeleteEvaluationResponse{Success: rpcResp.Success})
}
